name: WireGuard example

on:
  workflow_dispatch:

jobs:
  wireguard_example:
    runs-on: ubuntu-latest
    
    steps:

      - run: sudo apt install wireguard

      - name: Coping Private Key
        run: echo "${{ secrets.WG_FILE }}" > wg0.conf

      - name: Config tunnel
        run: sudo wg-quick up ./wg0.conf
      
   

      - run: curl -vvv http://10.13.13.1