name: WireGuard example

on:
  workflow_dispatch:

jobs:
  wireguard_example:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install wireguard

      - run: echo "$" > privatekey

      - run: sudo ip link add dev wg0 type wireguard

      - run: sudo ip address add dev wg0 10.13.13.2 peer 10.13.13.1

      - run: sudo wg set wg0 listen-port 51820 private-key privatekey peer 3afSK4iK6xoX2wsz1D51Y2aAwN4XUqYz372soJ2cvWg= allowed-ips 0.0.0.0/0 endpoint 23.233..177.17:51820

      - run: sudo ip link set up dev wg0

      - run: curl -vvv http://10.13.13.1