name: WireGuard example

on:
  workflow_dispatch:

jobs:
  wireguard_example:
    runs-on: ubuntu-latest
    
    steps:

      - run: sudo apt install wireguard

      - name: Coping Private Key
        env:
          wg_config: ${{ secrets.WG_FILE}}
        run: echo privatekey > ./wg_test.conf

      - name: Config tunnel
        run: wg setconfig wg0 wg_test.conf
      
   

      - run: curl -vvv http://10.13.13.1