name: WireGuard example

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up WireGuard
        uses: egor-tensin/setup-wireguard@v1
        with:
            endpoint: 23.233.177.77:51820
            endpoint_public_key: 3afSK4iK6xoX2wsz1D51Y2aAwN4XUqYz372soJ2cvWg=
            ips: 10.13.13.2/32
            allowed_ips: 0.0.0.0/0, ::0/0
            private_key: YGY/tqaq1+QLykdyia13mMWgQw8IDRszRMplPdhHhmM=
            preshared_key: wRcPGw0NhkEpdO4kxQ0f1Owdyj6A2tsiOHcnR5g1j88=
  
      - name: 
        run: curl -I 10.13.13.1