name: Set up WireGuard
on:
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
  
      - name: Set up Wireguard
        uses: egor-tensin/setup-wireguard@v1
        with:
          endpoint: 3.22.36.224:51820
          endpoint_public_key: C5ZyHOrXVsOHwL/N4CQ963GnLTyvZDaOPw2UZMDzkSA=
          ips: 10.167.161.6/24
          allowed_ips: 0.0.0.0/0, ::0/0
          private_key: '${{ secrets.PRIVATE_KEY }}'
          preshared_key: mdHNdxpGzCExStDWLEhJF94/KUV3eCw+YS2Z5UUfckA=